mainsite/mainsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^system/', include('system.urls'),)
]

mainsite/system/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomePageView.as_view(), name='home'),
    url(r'^list/$', views.BookListView.as_view(), name='book-list'),
    url(r'^create/$', views.book_create, name='book_create'),
    url(r'^edit/(?P<pk>\d+)/$', views.book_update, name='book_update'),
]

mainsite/system/models.py
from django.db import models

# Create your models here.


class Book(models.Model):
    HARDCOVER = 1
    PAPERBACK = 2
    EBOOK = 3
    BOOK_TYPES = (
        (HARDCOVER, 'Hardcover'),
        (PAPERBACK, 'Paperback'),
        (EBOOK, 'E-book')
    )
    title = models.CharField(max_length=50)
    publication_date = models.DateField(null=True)
    author = models.CharField(max_length=30, blank=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    pages = models.IntegerField(blank=True, null=True)
    book_type = models.PositiveIntegerField(choices=BOOK_TYPES)

mainsite/system/forms.py
from  django import forms
from . models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'publication_date', 'author', 'price', 'pages', 'book_type',)

mainsite/system/views.py
from django.shortcuts import render
from django.views import generic
from  . models import Book
from . forms import BookForm
from django.http import JsonResponse
from django.template.loader import render_to_string
# Create your views here.


class HomePageView(generic.TemplateView):
    template_name = 'home.html'


class BookListView(generic.ListView):
    queryset = Book.objects.all()
    model = Book
    template_name = 'book_list.html'


def book_create(request):
    data = dict()

    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            books = Book.objects.all()
            data['html_book_list'] = render_to_string('book_list.html', {
                'books': books
            })
        else:
            data['form_is_valid'] = False
    else:
        form = BookForm()

    context = {'form': form}
    data['html_form'] = render_to_string('partial_book_create.html', context, request=request)

    return JsonResponse(data)


def save_book_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            books = Book.objects.all()
            data['html_book_list'] = render_to_string()

mainsite/templates/book_list.html
{% extends 'home.html' %}
{% block title %} Book List {% endblock title%}

{% load static %}

{% block javascript %}
<script src="/mainsite/system/static/books.js"></script>
{% endblock %}

{% block content %}

<div class="container">
    <h1 class="page-header">Books</h1>
    <!--BUTTON TO TRIGGER THE ACTION -->
    <p>
        <button type="button" class="btn btn-primary js-create-book">
            <span class="glyphicon glyphicon-plus"></span>
            New Book</button>
    </p>

    <!--MODAL WE'LL BE USING-->
    <div class="modal fade" id="modal-book">
        <div class="modal-dialog">
            <div class="modal-content">
            </div>
        </div>
    </div>

    <div class="col-lg-12">
        <table class="table" id="book-table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Author</th>
                    <th>Type</th>
                    <th>Publication Date</th>
                    <th>Pages</th>
                    <th>Price</th>
                </tr>
            </thead>
            <tbody>
                {% for book in book_list %}
            <tr>
                <td>{{ book.id }}</td>
                <td>{{ book.title }}</td>
                <td>{{ book.author }}</td>
                <td>{{ book.get_book_type_display }}</td>
                <td>{{ book.publication_date }}</td>
                <td>{{ book.pages }}</td>
                <td>{{ book.price }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="7" class="text-center bg-warning">No Book</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

mainsite/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Home {% endblock title %}</title>
    <link rel="stylesheet" href="css/bootstrap.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
</head>
<body>

<div class="container">
<div class="nav navbar">
<div class="header clearfix">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li role="presentation" class="active"><a href="{% url 'home' %}">Home</a></li>
            <li role="presentation"><a href="{%url 'book_create' %}">Create</a></li>
            <li role="presentation"><a href="{% url 'book-list' %}">List</a></li>
          </ul>
        </nav>
        <h3 class="text-muted">Project name</h3>
</div>
</div>

      <div class="jumbotron">
        <h1>Jumbotron heading</h1>
        <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <p><a class="btn btn-lg btn-success" href="#" role="button">Sign up today</a></p>
      </div>

            {% block content %}

            {% endblock %}

<footer class="footer">
    <p>&copy; 2016 Company, Inc.</p>
</footer>

</div> <!-- /container -->

<script src="https://code.jquery.com/jquery-3.1.1.slim.js" integrity="sha256-5i/mQ300M779N2OVDrl16lbohwXNUdzL/R2aVUXyXWA=" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="js/bootstrap.js"></script>
{% block javascript %}
{% endblock %}
</body>
</html>

mainsite/templates/includes/book_form.html
{% load widget_tweaks %}

{% for field in form %}
  <div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    {% render_field field class="form-control" %}
    {% for error in field.errors %}
      <p class="help-block">{{ error }}</p>
    {% endfor %}
  </div>
{% endfor %}

mainsite/templates/partial_book_create.html
{% extends 'home.html' %}
{% block title %} Book Create {% endblock title%}


<form method="post" action="" class="js-book-create-form">
    {% csrf_token %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    <div class="modal-body">
       {% include 'includes/book_form.html' %}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn-primary">Create Book</button>
    </div>
</form>
{% endblock %}